spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: abe73370
  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true

